stages:
  - test
  - testCoverage
  - build
  - e2e-test

variables:
  NFS: "/nfs/general"
  TARGET_DIR: "$NFS/mera-artifacts/mera-${CI_COMMIT_SHA}"

test all:
  stage: test
  script:
    - sbt clean test

pages:
  stage: testCoverage
  script:
    - sbt clean coverage test 
    - sbt coverageReport
    - sbt coverageAggregate
    - mv target/scala-2.12/scoverage-report/ public/
  artifacts:
    paths: 
      - public
    expire_in: 30 days

build all:
  stage: build
  only:
    - master
  script:
    - sbt assembly
    - rm -rf $TARGET_DIR
    - cp -r artifacts $TARGET_DIR
