stages:
  - test
  - testCoverage
  - build
  - e2e-test

variables:
  NFS: "/nfs/general"
  LATEST: "$NFS/mera-artifacts-latest"

test all:
  stage: test
  script:
    - sbt clean test

pages:
  stage: testCoverage
  script:
    - sbt clean coverage test 
    - sbt coverageReport
    - sbt coverageAggregate
    - mv target/scala-2.12/scoverage-report/ public/
  artifacts:
    paths: 
      - public
    expire_in: 30 days

build all:
  stage: build
  only:
    - master
  script:
    - sbt assembly
    - cp -r artifacts "$NFS/$(date '+mera-artifacts_%Y-%m-%d_%H:%M:%S')"
    - rm -rf $LATEST
    - ln -s $(find $NFS -maxdepth 1 -name "mera-artifacts*" -type d -printf "%C@ %p\n" | sort -rn | head -n 1 | awk '{print $2}') $LATEST

end-to-end test:
  stage: e2e-test
  when: manual
  script:
    - mkdir -p flink
    - cp $NFS/flink-dist.tar.gz ./flink
    - cd flink
    - tar zxvf flink-dist.tar.gz
    - cd ..
    - python3 mera_run.py --libJar $LATEST/mera-reporter-0.1-SNAPSHOT.jar --jobJar $LATEST/three-stage-word-count-0.1-SNAPSHOT.jar --monitorJar $LATEST/mera-monitor-0.1-SNAPSHOT.jar --flinkDir flink/
